version: "3.9"

services:

  mongodb:
    image: docker.io/library/mongo:7
    container_name: palmpay-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: palmpay-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env
    restart: unless-stopped

  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
    interval: 30s
    retries: 3

volumes:
  mongo_data: